### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by jamesiri** [aws-robotics/monitoringmessages-ros1#14]
You have no license for the repo. This makes it difficult to understand what terms I can use this software.

**Comment by raghaprasad** [comment]
We do provide an actual copy: https://github.com/aws-robotics/monitoringmessages-ros1/blob/master/ros_monitoring_msgs/LICENSE.txt

In general should we be moving the LICENSE files to the root folder? In some cases (e.g the sample applications) it does not make sense. Let us know if this a problem as we will clean up across all repos.
